runtime: nodejs10 # For Node.js 8, use runtime: nodejs8
instance_class: F2

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

  beta settings:
      cloud_sql_instances: autocomplete-tinner:us-central1:store